"""Import animated GIF cards without renumbering existing cards or editing sources.

Run again after adding GIFs to the source folder. The catalog retains previous
IDs/volumes even when files are renamed, reordered or removed from that folder.
Requires Pillow for animation validation only; asset bytes are copied unchanged.
"""
import argparse
import hashlib
import json
import shutil
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / 'tool' / 'celestial_catalog.json'
DEST = ROOT / 'assets' / 'celestials'

def dart(value):
    return "'" + value.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$') + "'"

def reactions(name):
    lower = name.lower()
    if 'gato pez' in lower:
        return '¡Un michi submarino! ¡Wow!', '¡Ese pez tiene bigotes!'
    if any(w in lower for w in ['dance', 'baile', 'dansadur']):
        return '¡Ese pasito es celestial!', '¡Wow! ¡Quiero bailar así!'
    if 'perro' in lower:
        return '¡Ese perrito rompió el universo!', '¡Wow, un amigo celestial!'
    if 'goku' in lower or 'karate' in lower:
        return '¡Ese poder no cabe en el sobre!', '¡Wow! ¡Nivel celestial!'
    if 'trade' in lower:
        return '¡La oferta más celestial!', '¡Wow! Esta sí es un tesoro.'
    return f'¡{name}! ¡Qué carta más increíble!', '¡Wow! ¡Llegó desde las estrellas!'

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=Path.home() / 'Downloads' / 'CARTAS CELESTIALES')
    args = parser.parse_args()
    if not args.source.is_dir():
        parser.error(f'No existe la carpeta: {args.source}')
    entries = json.loads(CATALOG.read_text(encoding='utf-8')) if CATALOG.exists() else []
    DEST.mkdir(parents=True, exist_ok=True)
    imported = 0
    for source in sorted(args.source.glob('*.gif'), key=lambda f: f.name.casefold()):
        digest = hashlib.sha256(source.read_bytes()).hexdigest()
        existing = next((e for e in entries if e['sha256'] == digest), None)
        if existing:
            if not (ROOT / existing['asset']).is_file():
                existing['asset'] = f"assets/celestials/celestial_{existing['id']}.gif"
                shutil.copyfile(source, ROOT / existing['asset'])
            continue
        existing = next((e for e in entries if e['source'] == source.name), None)
        with Image.open(source) as image:
            frames, duration = image.n_frames, 0
            width, height = image.size
            if frames < 2:
                raise ValueError(f'{source.name}: el GIF debe tener varios fotogramas')
            for i in range(frames):
                image.seek(i)
                image.load()
                duration += image.info.get('duration', 100) or 100
        if not existing:
            card_id = max([9999] + [e['id'] for e in entries]) + 1
            volume = 1 if sum(e['volume'] == 1 for e in entries) <= sum(e['volume'] == 2 for e in entries) else 2
            name = {'robot dice nigga': 'Robot parlante', 'sin SEMEEEEN': 'El grito inesperado'}.get(source.stem, source.stem[:1].upper() + source.stem[1:])
            maru, lady = reactions(name)
            existing = dict(id=card_id, volume=volume, name=name,
                            asset=f'assets/celestials/celestial_{card_id}.gif',
                            maru=maru, lady=lady)
            entries.append(existing)
        old_asset = ROOT / existing['asset']
        existing.update(asset=f"assets/celestials/celestial_{existing['id']}.gif",
                        source=source.name, sha256=digest, width=width, height=height,
                        frames=frames, durationMs=duration, bytes=source.stat().st_size)
        shutil.copyfile(source, ROOT / existing['asset'])
        if old_asset != ROOT / existing['asset'] and old_asset.parent == DEST:
            old_asset.unlink(missing_ok=True)
        imported += 1
    CATALOG.write_text(json.dumps(entries, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    lines = ['// Generated by tool/import_celestials.py. IDs and volumes are permanent.',
             'class CelestialCardDefinition {',
             '  final int id, volume, frames, durationMs;',
             '  final String name, asset, maru, lady;',
             '  const CelestialCardDefinition(this.id, this.volume, this.name, this.asset, this.frames, this.durationMs, this.maru, this.lady);',
             '}', 'const celestialCatalog = <CelestialCardDefinition>[']
    for e in entries:
        lines.append(f"  CelestialCardDefinition({e['id']}, {e['volume']}, {dart(e['name'])}, {dart(e['asset'])}, {e['frames']}, {e['durationMs']}, {dart(e['maru'])}, {dart(e['lady'])}),")
    lines.append('];')
    (ROOT / 'lib' / 'celestial_cards.dart').write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'{imported} imported; {len(entries)} celestial cards: ' + ', '.join(f'Vol. {v}: {sum(e["volume"] == v for e in entries)}' for v in [1, 2]))

if __name__ == '__main__':
    main()
