"""Add new meme images without changing IDs of existing collected cards."""
import argparse
import json
import re
from pathlib import Path
from PIL import Image, ImageOps, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / "assets" / "memes"
CATALOG = ROOT / "tool" / "meme_catalog.json"
DART = ROOT / "lib" / "meme_cards.dart"
EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}

def is_supported_image(path):
    if path.suffix.lower() in EXTENSIONS:
        return True
    if path.suffix:
        return False
    try:
        with Image.open(path) as image:
            image.verify()
        return True
    except (OSError, ValueError):
        return False

def dart_string(value):
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$") + "'"

def existing_catalog():
    if CATALOG.exists():
        return json.loads(CATALOG.read_text(encoding="utf-8"))
    if DART.exists():
        source = DART.read_text(encoding="utf-8")
        names_block = source.split("const memeNames = [", 1)[1].split("];", 1)[0]
        names = [m.group(1).replace("\\'", "'").replace("\\$", "$")
                 for line in names_block.splitlines()
                 if (m := re.fullmatch(r"\s*'(.*)',\s*", line))]
        return [{"name": name, "asset": f"assets/memes/meme_{i:02d}.webp"}
                for i, name in enumerate(names)]
    return []

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=Path.home() / "Downloads" / "memes")
    parser.add_argument("--volume", type=int, default=1)
    args = parser.parse_args()
    if not args.source.is_dir():
        parser.error(f"Carpeta no encontrada: {args.source}")
    DEST.mkdir(parents=True, exist_ok=True)
    catalog = existing_catalog()
    known = {entry["name"].casefold() for entry in catalog if entry.get("volume", 1) == args.volume}
    files = sorted((p for p in args.source.iterdir() if p.is_file() and is_supported_image(p)),
                   key=lambda p: p.name.casefold())
    added = []
    for source in files:
        if source.stem.casefold() in known:
            continue
        with Image.open(source) as original:
            image = ImageOps.exif_transpose(original).convert("RGB")
            image.thumbnail((960, 960), Image.Resampling.LANCZOS)
            asset = f"assets/memes/meme_{len(catalog):02d}.webp"
            image.save(ROOT / asset, "WEBP", quality=83, method=6)
        catalog.append({"name": source.stem, "asset": asset, "volume": args.volume})
        known.add(source.stem.casefold())
        added.append(source.stem)
    for entry in catalog:
        if not (ROOT / entry["asset"]).is_file():
            raise FileNotFoundError(f"Falta imagen de una carta existente: {entry['asset']}")
    CATALOG.write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    DART.write_text(
        "// Generated by tool/import_memes.py. Order and IDs are stable.\n"
        "const memeNames = [\n" + "".join(f"  {dart_string(e['name'])},\n" for e in catalog)
        + "];\n\nconst memeAssets = [\n"
        + "".join(f"  {dart_string(e['asset'])},\n" for e in catalog) + "];\n\nconst memeVolumes = [\n"
        + "".join(f"  {e.get('volume', 1)},\n" for e in catalog) + "];\n",
        encoding="utf-8")
    sheet = Image.new("RGB", (1000, ((len(files) + 5) // 6) * 175), "#e9e2f0")
    draw = ImageDraw.Draw(sheet)
    for index, source in enumerate(files):
        with Image.open(source) as original:
            image = ImageOps.exif_transpose(original).convert("RGB")
            image.thumbnail((150, 140), Image.Resampling.LANCZOS)
        x, y = (index % 6) * 166 + 8, (index // 6) * 175 + 5
        sheet.paste(image, (x + (150 - image.width) // 2, y))
        draw.text((x, y + 143), source.stem[:23], fill="#251a30")
    sheet.save(ROOT / "tool" / "meme_contact_sheet.jpg", quality=85)
    print(f"Cartas: {len(catalog)}. Nuevas: {len(added)}." +
          (" Agregadas: " + ", ".join(added) if added else ""))

if __name__ == "__main__":
    main()
